import { hydratePlannerData } from './planUtils'
import type { PlannerData } from './types'

const samplePlan: PlannerData = hydratePlannerData({
  eventName: 'Lucie & Marc',
  rooms: [
    { id: 'room-main', name: 'Salle principale', notes: 'Dinner and speeches' },
    { id: 'room-garden', name: 'Veranda', notes: 'Calmer corner for family' },
  ],
  tables: [
    {
      id: 'table-head',
      roomId: 'room-main',
      name: 'Head table',
      shape: 'oval',
      seatCount: 6,
      notes: 'Closest friends and witnesses',
    },
    {
      id: 'table-family',
      roomId: 'room-garden',
      name: 'Family table',
      shape: 'round',
      seatCount: 8,
      notes: 'Parents, siblings, grandparents',
    },
    {
      id: 'table-friends',
      roomId: 'room-main',
      name: 'Friends table',
      shape: 'round',
      seatCount: 8,
      notes: 'College and travel friends',
    },
    {
      id: 'table-kids',
      roomId: 'room-garden',
      name: 'Kids corner',
      shape: 'kids',
      seatCount: 6,
      notes: 'Optional dedicated table',
    },
  ],
  guests: [
    {
      id: 'guest-alice',
      name: 'Alice',
      age: 31,
      circle: 'Bride side',
      partnerId: 'guest-noah',
      tags: ['friends', 'travel'],
      notes: 'Loves lively tables',
    },
    {
      id: 'guest-noah',
      name: 'Noah',
      age: 33,
      circle: 'Bride side',
      partnerId: 'guest-alice',
      tags: ['friends', 'travel'],
      notes: '',
    },
    {
      id: 'guest-emma',
      name: 'Emma',
      age: 29,
      circle: 'College friends',
      partnerId: 'guest-lucas',
      tags: ['friends', 'college'],
      notes: '',
    },
    {
      id: 'guest-lucas',
      name: 'Lucas',
      age: 30,
      circle: 'College friends',
      partnerId: 'guest-emma',
      tags: ['friends', 'college'],
      notes: '',
    },
    {
      id: 'guest-claire',
      name: 'Claire',
      age: 58,
      circle: 'Family',
      partnerId: 'guest-pierre',
      tags: ['family'],
      notes: 'Would appreciate a quieter table',
    },
    {
      id: 'guest-pierre',
      name: 'Pierre',
      age: 60,
      circle: 'Family',
      partnerId: 'guest-claire',
      tags: ['family'],
      notes: '',
    },
    {
      id: 'guest-sophie',
      name: 'Sophie',
      age: 26,
      circle: 'Work friends',
      partnerId: null,
      tags: ['friends', 'dancefloor'],
      notes: 'Can help animate a shy table',
    },
    {
      id: 'guest-jules',
      name: 'Jules',
      age: 27,
      circle: 'Work friends',
      partnerId: null,
      tags: ['friends', 'dancefloor'],
      notes: '',
    },
    {
      id: 'guest-lea',
      name: 'Lea',
      age: 11,
      circle: 'Family',
      partnerId: null,
      tags: ['kids'],
      notes: 'Feels comfortable with other children',
    },
    {
      id: 'guest-tom',
      name: 'Tom',
      age: 9,
      circle: 'Family',
      partnerId: null,
      tags: ['kids'],
      notes: '',
    },
    {
      id: 'guest-henri',
      name: 'Henri',
      age: 67,
      circle: 'Family',
      partnerId: null,
      tags: ['family'],
      notes: 'Prefers calm conversation',
    },
    {
      id: 'guest-camille',
      name: 'Camille',
      age: 32,
      circle: 'Bride side',
      partnerId: null,
      tags: ['friends', 'travel'],
      notes: '',
    },
  ],
  affinities: [
    {
      id: 'aff-1',
      guestAId: 'guest-alice',
      guestBId: 'guest-camille',
      score: 80,
      note: 'Best friends',
    },
    {
      id: 'aff-2',
      guestAId: 'guest-emma',
      guestBId: 'guest-lucas',
      score: 95,
      note: 'Couple',
    },
    {
      id: 'aff-3',
      guestAId: 'guest-sophie',
      guestBId: 'guest-jules',
      score: 75,
      note: 'Great together',
    },
    {
      id: 'aff-4',
      guestAId: 'guest-claire',
      guestBId: 'guest-henri',
      score: 55,
      note: 'Family branch gets along well',
    },
    {
      id: 'aff-5',
      guestAId: 'guest-lea',
      guestBId: 'guest-tom',
      score: 88,
      note: 'Kids table buddies',
    },
    {
      id: 'aff-6',
      guestAId: 'guest-sophie',
      guestBId: 'guest-henri',
      score: -65,
      note: 'Very different energy',
    },
    {
      id: 'aff-7',
      guestAId: 'guest-camille',
      guestBId: 'guest-claire',
      score: 30,
      note: 'Lovely conversation match',
    },
    {
      id: 'aff-8',
      guestAId: 'guest-jules',
      guestBId: 'guest-henri',
      score: -100,
      note: 'Avoid at all costs',
    },
  ],
  seating: {
    'table-head': ['guest-alice', 'guest-noah', 'guest-camille', null, null, null],
    'table-family': [
      'guest-claire',
      'guest-pierre',
      'guest-henri',
      null,
      null,
      null,
      null,
      null,
    ],
    'table-friends': ['guest-emma', 'guest-lucas', 'guest-sophie', 'guest-jules', null, null, null, null],
    'table-kids': ['guest-lea', 'guest-tom', null, null, null, null],
  },
})

export default samplePlan
